# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbMovies',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=50)),
                ('m_othername', models.CharField(blank=True, max_length=512, null=True)),
                ('m_cover', models.CharField(blank=True, max_length=100, null=True)),
                ('m_actor', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_director', models.CharField(blank=True, max_length=512, null=True)),
                ('m_classify', models.CharField(blank=True, max_length=40, null=True)),
                ('m_area', models.CharField(blank=True, max_length=20, null=True)),
                ('m_language', models.CharField(blank=True, max_length=20, null=True)),
                ('m_releasetime', models.CharField(blank=True, max_length=50, null=True)),
                ('m_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('m_score', models.CharField(blank=True, max_length=10, null=True)),
                ('m_shortcomment', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_synopsis', models.CharField(blank=True, max_length=4096, null=True)),
                ('m_linkinfo', models.CharField(blank=True, db_column='m_linkInfo', max_length=8192, null=True)),
                ('m_info', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_userid', models.CharField(blank=True, max_length=10, null=True)),
                ('m_plays', models.IntegerField(blank=True, null=True)),
                ('m_like', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUsers',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=12)),
                ('u_pwd', models.CharField(max_length=20)),
                ('u_gender', models.IntegerField()),
                ('u_age', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('u_vip', models.IntegerField(blank=True, null=True)),
                ('u_email', models.CharField(max_length=30)),
                ('u_likemovies', models.CharField(blank=True, max_length=30, null=True)),
                ('u_duration', models.CharField(blank=True, max_length=4, null=True)),
                ('u_recording', models.CharField(blank=True, max_length=30, null=True)),
                ('u_recommendmovie', models.CharField(blank=True, db_column='u_recommendMovie', max_length=30, null=True)),
            ],
            options={
                'db_table': 'tb_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestMovies',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=50)),
                ('m_othername', models.CharField(blank=True, max_length=512, null=True)),
                ('m_cover', models.CharField(blank=True, max_length=100, null=True)),
                ('m_actor', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_director', models.CharField(blank=True, max_length=200, null=True)),
                ('m_classify', models.CharField(blank=True, max_length=40, null=True)),
                ('m_area', models.CharField(blank=True, max_length=20, null=True)),
                ('m_language', models.CharField(blank=True, max_length=20, null=True)),
                ('m_releasetime', models.CharField(blank=True, max_length=50, null=True)),
                ('m_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('m_score', models.CharField(blank=True, max_length=10, null=True)),
                ('m_shortcomment', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_synopsis', models.CharField(blank=True, max_length=5120, null=True)),
                ('m_linkinfo', models.CharField(blank=True, db_column='m_linkInfo', max_length=8192, null=True)),
                ('m_info', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_userid', models.CharField(blank=True, max_length=10, null=True)),
                ('m_plays', models.IntegerField(blank=True, null=True)),
                ('m_like', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_movies',
                'managed': False,
            },
        ),
    ]
